### ISSUE TITLE
compile error at importing package

### ISSUE THREAD

**Issue by drkhodakarami** [needle-mirror/com.unity.graphtools.foundation#1]
Hi
I imported package with version 0.11.2-preview
At importing to the project, I get a compile error : 

Library\PackageCache\com.unity.graphtools.foundation@0.11.2-preview\Editor\InternalBridge\GraphViewStaticBridge.cs(290,39): error CS7036: There is no argument given that corresponds to the required formal parameter 'contextType' of 'PointerDeviceState.GetPointerPosition(int, ContextType)'

**Comment by marwie** [comment]
Hello,

unfortunately we cant process bug reports (this is not an official Unity repository, we just mirror new package versions).
Please report bugs using [the official Unity bug reporter](https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-)
